# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with pycodestyle
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          find . -name "*.py" | xargs pycodestyle --ignore=E501,W503
          # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          exit 0
      - name: Test with pycodestyle
        run: |
          echo "Running tests..."
          python3 -m unittest discover tests
